stages:
  - deploy

deploy_to_ec2:
  stage: deploy
  image: ubuntu:latest

  before_script:
    - apt-get update -y
    - apt-get install -y openssh-client rsync

    # SSH setup
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519

    # host verify avoid
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

  script:
    # deploy files
    - rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519" ./ $EC2_USER@$EC2_HOST:/var/www/html

    # restart nginx
    - ssh -i ~/.ssh/id_ed25519 $EC2_USER@$EC2_HOST "sudo systemctl restart nginx"