stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install -y openssh-client

    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > key.pem
    - chmod 600 key.pem

    - ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST "
        sudo rm -rf /var/www/html/* &&
        git clone https://github.com/Nitishkrsahu/aws-git-2 /tmp/app &&
        sudo cp -r /tmp/app/public/* /var/www/html/ &&
        sudo systemctl restart nginx
      "

  only:
    - main